from ubuntu:latest

WORKDIR backend-svr

RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

RUN sudo dpkg -i packages-microsoft-prod.deb

RUN sudo add-apt-repository universe

RUN sudo apt install apt-transport-https

RUN sudo apt update

RUN sudo apt install dotnet-sdk-2.2

COPY ./ ./

RUN dotnet restore

RUN dotnet build

EXPOSE 5000:5000

CMD [ "dotnet", "run" ]