version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    image: nginx # specify the directory of the Dockerfile
    ports:
      - "80:80" # specify port forewarding
    depends_on:
      - backendsvr
      - backendsvr2
      - backendsvr3  
    links:
      - backendsvr # link this service to the database service
      - backendsvr2
      - backendsvr3

  backendsvr: #name of the second service
    image: backendsvr # specify the directory of the Dockerfile
    ports:
      - "8080:8080" #specify ports forewarding
    depends_on:
      - mysql
    links:
      - mysql # link this service to the database service

  backendsvr2: #name of the second service
    image: backendsvr2 # specify the directory of the Dockerfile
    ports:
      - "8081:8081" #specify ports forewarding
    depends_on:
      - mysql
    links:
      - mysql # link this service to the database service
  
  backendsvr3: #name of the second service
    image: backendsvr3 # specify the directory of the Dockerfile
    ports:
      - "5000:5000" #specify ports forewarding
    depends_on:
      - mongodb
    links:
      - mongodb # link this service to the database service    
  
  mysql: # name of the third service
    image: mysql # specify image to build container from
    ports:
      - "3306:3306" # specify port forewarding
      - "33060:33060"    

  mongodb: # name of the third service
    image: mongodb # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding