FROM python:3

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

#COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

COPY ./ ./

ENV FLASK_SECRET_KEY sdfdsf3424432dsffdsf
ENV MONGODB_URL mongodb://mongodb:27017/testdb
ENV FLASK_PORT 5000

RUN pip install -r requirements.txt

EXPOSE 5000:5000

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]
